trigger:
  - teste-branch
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    displayName: "Build e Push para ACR"
    jobs:
      - job: BuildAndPush
        steps:
          - task: Docker@2
            displayName: "Build e Push da imagem"
            inputs:
              containerRegistry: "javamssqlrm559982"
              repository:        "ecoorbit-deploy"
              command:           "buildAndPush"
              Dockerfile:        "**/Dockerfile"
              tags: |
                $(Build.BuildId)
                latest